version: '3.8'

services:
  bot:
    build: .
    container_name: tg_demo_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWM_API_KEY=${OWM_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "10000:10000"   # порт для Flask healthcheck