# Словарь разговорных названий валют (ВСЕ КЛЮЧИ — В НИЖНЕМ РЕГИСТРЕ)
POPULAR_NAMES = {
    # ========== КРОНЫ ==========
    "crown": "DKK",
    "crowns": "DKK",
    "danish crown": "DKK",
    "danish crowns": "DKK",
    "danish krone": "DKK",
    "danish kroner": "DKK",
    "датская крона": "DKK",
    "датские кроны": "DKK",
    "датских крон": "DKK",
    "czech crown": "CZK",
    "czech crowns": "CZK",
    "czech koruna": "CZK",
    "koruna": "CZK",
    "чешская крона": "CZK",
    "чешские кроны": "CZK",
    "чешских крон": "CZK",
    "krone": "NOK",
    "kroner": "NOK",
    "norwegian krone": "NOK",
    "норвежская крона": "NOK",
    "норвежские кроны": "NOK",
    "норвежских крон": "NOK",
    "swedish krona": "SEK",
    "swedish kronor": "SEK",
    "шведская крона": "SEK",
    "шведские кроны": "SEK",
    "шведских крон": "SEK",
    # ========== ЕВРО ==========
    "euro": "EUR",
    "euros": "EUR",
    "евро": "EUR",
    "eur": "EUR",
    # ========== ДОЛЛАРЫ ==========
    "buck": "USD",
    "bucks": "USD",
    "greenback": "USD",
    "dollar": "USD",
    "dollars": "USD",
    "доллар": "USD",
    "доллара": "USD",
    "долларов": "USD",
    "доллары": "USD",
    "us dollar": "USD",
    "us dollars": "USD",
    "доллар сша": "USD",
    "доллара сша": "USD",
    "долларов сша": "USD",
    "доллары сша": "USD",
    "американский доллар": "USD",
    "американских долларов": "USD",
    "американские доллары": "USD",
    "aussie": "AUD",
    "australian dollar": "AUD",
    "australian dollars": "AUD",
    "австралийский доллар": "AUD",
    "австралийских долларов": "AUD",
    "австралийские доллары": "AUD",
    "loonie": "CAD",
    "canadian dollar": "CAD",
    "canadian dollars": "CAD",
    "канадский доллар": "CAD",
    "канадских долларов": "CAD",
    "канадские доллары": "CAD",
    "kiwi": "NZD",
    "new zealand dollar": "NZD",
    "new zealand dollars": "NZD",
    "новозеландский доллар": "NZD",
    "новозеландских долларов": "NZD",
    "новозеландские доллары": "NZD",
    "hong kong dollar": "HKD",
    "hong kong dollars": "HKD",
    "гонконгский доллар": "HKD",
    "гонконгских долларов": "HKD",
    "гонконгские доллары": "HKD",
    "singapore dollar": "SGD",
    "singapore dollars": "SGD",
    "сингапурский доллар": "SGD",
    "сингапурских долларов": "SGD",
    "сингапурские доллары": "SGD",
    # ========== ФУНТЫ ==========
    "quid": "GBP",
    "pound sterling": "GBP",
    "pound": "GBP",
    "pounds": "GBP",
    "фунт": "GBP",
    "фунта": "GBP",
    "фунтов": "GBP",
    "фунты": "GBP",
    "фунт стерлингов": "GBP",
    "фунта стерлингов": "GBP",
    "фунтов стерлингов": "GBP",
    "британский фунт": "GBP",
    "британских фунтов": "GBP",
    # ========== РУБЛИ ==========
    "rub": "RUB",
    "ruble": "RUB",
    "rubles": "RUB",
    "rouble": "RUB",
    "roubles": "RUB",
    "рубль": "RUB",
    "рубля": "RUB",
    "рублей": "RUB",
    "рубли": "RUB",
    "рублях": "RUB",
    "российский рубль": "RUB",
    "российских рублей": "RUB",
    # ========== АЗИАТСКИЕ ==========
    "бат": "THB",
    "baht": "THB",
    "bat": "THB",
    "bath": "THB",
    "тайский бат": "THB",
    "тайских бат": "THB",
    "тайские баты": "THB",
    "yuan": "CNY",
    "renminbi": "CNY",
    "юань": "CNY",
    "юаня": "CNY",
    "юаней": "CNY",
    "китайский юань": "CNY",
    "китайских юаней": "CNY",
    "yen": "JPY",
    "йена": "JPY",
    "йен": "JPY",
    "йены": "JPY",
    "йенах": "JPY",
    "иена": "JPY",
    "иен": "JPY",
    "иены": "JPY",
    "японская йена": "JPY",
    "японских йен": "JPY",
    "tenge": "KZT",
    "тенге": "KZT",
    "казахстанский тенге": "KZT",
    "казахстанских тенге": "KZT",
    "rupee": "INR",
    "рупия": "INR",
    "рупии": "INR",
    "рупий": "INR",
    "индийская рупия": "INR",
    "индийских рупий": "INR",
    "rupiah": "IDR",
    "руппия": "IDR",
    "руппии": "IDR",
    "руппий": "IDR",
    "индонезийская рупия": "IDR",
    "индонезийских рупий": "IDR",
    "taka": "BDT",
    "така": "BDT",
    "бангладешская така": "BDT",
    "бангладешских так": "BDT",
    "kyat": "MMK",
    "кьят": "MMK",
    "кьята": "MMK",
    "кьятов": "MMK",
    "мьянманский кьят": "MMK",
    "мьянманских кьятов": "MMK",
    "riel": "KHR",
    "риэль": "KHR",
    "риэля": "KHR",
    "риэлей": "KHR",
    "камбоджийский риэль": "KHR",
    "камбоджийских риэлей": "KHR",
    "ringgit": "MYR",
    "ринггит": "MYR",
    "ринггита": "MYR",
    "ринггитов": "MYR",
    "малайзийский ринггит": "MYR",
    "малайзийских ринггитов": "MYR",
    "won": "KRW",
    "wons": "KRW",
    "вона": "KRW",
    "воны": "KRW",
    "вон": "KRW",
    "krw": "KRW",
    "южнокорейская вона": "KRW",
    "южнокорейских вон": "KRW",
    "корейская вона": "KRW",
    "корейских вон": "KRW",
    "som": "KGS",
    "soms": "KGS",
    "сом": "KGS",
    "сома": "KGS",
    "сомов": "KGS",
    "киргизский сом": "KGS",
    "киргизских сомов": "KGS",
    "сомони": "TJS",
    "таджикский сомони": "TJS",
    "таджикских сомони": "TJS",
    # ========== БЛИЖНЕВОСТОЧНЫЕ ==========
    "dirham": "AED",
    "дирхам": "AED",
    "дирхама": "AED",
    "дирхамов": "AED",
    "uae dirham": "AED",
    "emirati dirham": "AED",
    "дирхам оаэ": "AED",
    "дирхамов оаэ": "AED",
    "shekel": "ILS",
    "shekels": "ILS",
    "new shekel": "ILS",
    "new shekels": "ILS",
    "шекель": "ILS",
    "шекеля": "ILS",
    "шекелей": "ILS",
    "израильский шекель": "ILS",
    "израильских шекелей": "ILS",
    "lira": "TRY",
    "lire": "TRY",
    "liras": "TRY",
    "лира": "TRY",
    "лиры": "TRY",
    "лир": "TRY",
    "турецкая лира": "TRY",
    "турецких лир": "TRY",
    "rial": "IRR",
    "rials": "IRR",
    "риал": "IRR",
    "риала": "IRR",
    "риалов": "IRR",
    "iranian rial": "IRR",
    "иранский риал": "IRR",
    "иранских риалов": "IRR",
    "qatari riyal": "QAR",
    "qatari riyals": "QAR",
    "катарский риал": "QAR",
    "катарских риалов": "QAR",
    "saudi riyal": "SAR",
    "saudi riyals": "SAR",
    "саудовский риал": "SAR",
    "саудовских риалов": "SAR",
    "риал саудовской аравии": "SAR",
    # ========== АФРИКАНСКИЕ ==========
    "rand": "ZAR",
    "rands": "ZAR",
    "рэнд": "ZAR",
    "рэнда": "ZAR",
    "рэндов": "ZAR",
    "южноафриканский рэнд": "ZAR",
    "южноафриканских рэндов": "ZAR",
    "naira": "NGN",
    "nairas": "NGN",
    "найра": "NGN",
    "найры": "NGN",
    "найр": "NGN",
    "нигерийская найра": "NGN",
    "нигерийских найр": "NGN",
    "cedi": "GHS",
    "cedis": "GHS",
    "седи": "GHS",
    "ганский седи": "GHS",
    "ганских седи": "GHS",
    "shilling": "KES",
    "shillings": "KES",
    "kenyan shilling": "KES",
    "kenyan shillings": "KES",
    "шиллинг": "KES",
    "шиллинга": "KES",
    "шиллингов": "KES",
    "кенийский шиллинг": "KES",
    "кенийских шиллингов": "KES",
    "tanzanian shilling": "TZS",
    "tanzanian shillings": "TZS",
    "танзанийский шиллинг": "TZS",
    "танзанийских шиллингов": "TZS",
    "ugandan shilling": "UGX",
    "ugandan shillings": "UGX",
    "угандийский шиллинг": "UGX",
    "угандийских шиллингов": "UGX",
    "kwacha": "MWK",
    "kwachas": "MWK",
    "malawian kwacha": "MWK",
    "malawian kwachas": "MWK",
    "квача": "MWK",
    "квачи": "MWK",
    "квач": "MWK",
    "малавийская квача": "MWK",
    "малавийских квач": "MWK",
    "metical": "MZN",
    "meticals": "MZN",
    "метикал": "MZN",
    "метикала": "MZN",
    "метикалов": "MZN",
    "мозамбикский метикал": "MZN",
    "мозамбикских метикалов": "MZN",
    "pula": "BWP",
    "pulas": "BWP",
    "пула": "BWP",
    "ботсванская пула": "BWP",
    "ботсванских пул": "BWP",
    "birr": "ETB",
    "birrs": "ETB",
    "быр": "ETB",
    "быра": "ETB",
    "быров": "ETB",
    "эфиопский быр": "ETB",
    "эфиопских быров": "ETB",
    # ========== ЛАТИНСКАЯ АМЕРИКА ==========
    "peso": "MXN",
    "pesos": "MXN",
    "песо": "MXN",
    "мексиканское песо": "MXN",
    "мексиканских песо": "MXN",
    "cuban peso": "CUP",
    "cuban pesos": "CUP",
    "peso cubano": "CUP",
    "кубинское песо": "CUP",
    "кубинских песо": "CUP",
    "argentine peso": "ARS",
    "argentine pesos": "ARS",
    "аргентинское песо": "ARS",
    "аргентинских песо": "ARS",
    "chilean peso": "CLP",
    "chilean pesos": "CLP",
    "чилийское песо": "CLP",
    "чилийских песо": "CLP",
    "colombian peso": "COP",
    "colombian pesos": "COP",
    "колумбийское песо": "COP",
    "колумбийских песо": "COP",
    "uruguayan peso": "UYU",
    "uruguayan pesos": "UYU",
    "уругвайское песо": "UYU",
    "уругвайских песо": "UYU",
    "dominican peso": "DOP",
    "dominican pesos": "DOP",
    "доминиканское песо": "DOP",
    "доминиканских песо": "DOP",
    "philippine peso": "PHP",
    "philippine pesos": "PHP",
    "филиппинское песо": "PHP",
    "филиппинских песо": "PHP",
    "colon": "CRC",
    "colones": "CRC",
    "колон": "CRC",
    "колона": "CRC",
    "колонов": "CRC",
    "коста-риканский колон": "CRC",
    "коста-риканских колонов": "CRC",
    "cordoba": "NIO",
    "cordobas": "NIO",
    "кордоба": "NIO",
    "кордобы": "NIO",
    "кордоб": "NIO",
    "никарагуанская кордоба": "NIO",
    "никарагуанских кордоб": "NIO",
    "guarani": "PYG",
    "guaranis": "PYG",
    "гуарани": "PYG",
    "парагвайский гуарани": "PYG",
    "парагвайских гуарани": "PYG",
    "boliviano": "BOB",
    "bolivianos": "BOB",
    "боливиано": "BOB",
    "боливийский боливиано": "BOB",
    "боливийских боливиано": "BOB",
    "sol": "PEN",
    "soles": "PEN",
    "соль": "PEN",
    "соля": "PEN",
    "солей": "PEN",
    "перуанский соль": "PEN",
    "перуанских солей": "PEN",
    # ========== ЕВРОПА (ОСТАЛЬНЫЕ) ==========
    "forint": "HUF",
    "forints": "HUF",
    "форинт": "HUF",
    "форинта": "HUF",
    "форинтов": "HUF",
    "венгерский форинт": "HUF",
    "венгерских форинтов": "HUF",
    "zloty": "PLN",
    "zlotys": "PLN",
    "злотый": "PLN",
    "злотого": "PLN",
    "злотых": "PLN",
    "польский злотый": "PLN",
    "польских злотых": "PLN",
    "leu": "RON",
    "lei": "RON",
    "romanian leu": "RON",
    "romanian lei": "RON",
    "лей": "RON",
    "лея": "RON",
    "леев": "RON",
    "румынский лей": "RON",
    "румынских леев": "RON",
    "moldovan leu": "MDL",
    "moldovan lei": "MDL",
    "молдавский лей": "MDL",
    "молдавских леев": "MDL",
    # ========== ДИНАРЫ ==========
    "dinar": "KWD",
    "dinars": "KWD",
    "kuwaiti dinar": "KWD",
    "kuwaiti dinars": "KWD",
    "динар": "KWD",
    "динара": "KWD",
    "динаров": "KWD",
    "кувейтский динар": "KWD",
    "кувейтских динаров": "KWD",
    "bahraini dinar": "BHD",
    "bahraini dinars": "BHD",
    "бахрейнский динар": "BHD",
    "бахрейнских динаров": "BHD",
    "iraqi dinar": "IQD",
    "iraqi dinars": "IQD",
    "иракский динар": "IQD",
    "иракских динаров": "IQD",
    "jordanian dinar": "JOD",
    "jordanian dinars": "JOD",
    "иорданский динар": "JOD",
    "иорданских динаров": "JOD",
    "libyan dinar": "LYD",
    "libyan dinars": "LYD",
    "ливийский динар": "LYD",
    "ливийских динаров": "LYD",
    "tunisian dinar": "TND",
    "tunisian dinars": "TND",
    "тунисский динар": "TND",
    "тунисских динаров": "TND",
    "algerian dinar": "DZD",
    "algerian dinars": "DZD",
    "алжирский динар": "DZD",
    "алжирских динаров": "DZD",
    "serbian dinar": "RSD",
    "serbian dinars": "RSD",
    "сербский динар": "RSD",
    "сербских динаров": "RSD",
    # ========== ДРУГИЕ ==========
    "real": "BRL",
    "reals": "BRL",
    "реал": "BRL",
    "реала": "BRL",
    "реалов": "BRL",
    "бразильский реал": "BRL",
    "бразильских реалов": "BRL",
    "manat": "AZN",
    "manats": "AZN",
    "манат": "AZN",
    "маната": "AZN",
    "манатов": "AZN",
    "азербайджанский манат": "AZN",
    "азербайджанских манатов": "AZN",
    "turkmenistan manat": "TMT",
    "turkmenistan manats": "TMT",
    "туркменский манат": "TMT",
    "туркменских манатов": "TMT",
    "dram": "AMD",
    "drams": "AMD",
    "драм": "AMD",
    "драма": "AMD",
    "драмов": "AMD",
    "армянский драм": "AMD",
    "армянских драмов": "AMD",
    "georgian lari": "GEL",
    "georgian laris": "GEL",
    "лари": "GEL",
    "грузинский лари": "GEL",
    "грузинских лари": "GEL",
    "uzbek som": "UZS",
    "uzbek soms": "UZS",
    "узбекский сум": "UZS",
    "узбекских сумов": "UZS",
    "kyrgyz som": "KGS",
    "kyrgyz soms": "KGS",
    "tajik somoni": "TJS",
    "tajik somonis": "TJS",
    "xdr": "XDR",
    "sdr": "XDR",
    "special drawing right": "XDR",
    "special drawing rights": "XDR",
    "сдр": "XDR",
    "специальные права заимствования": "XDR",
}
